app:
  name: "InfoWatchdog Environment Monitor"
  version: "1.0.0"

collectors:
  reddit:
    enabled: true
    subreddits: ["environment", "climate", "sustainability", "renewableenergy", "ClimateChange", "solar", "wind"]
    limit: 25
    sort_type: "hot"
    time_filter: "day"

  rss:
    enabled: true
    timeout: 30
    feeds:
      - url: "https://cleantechnica.com/feed/"
        name: "CleanTechnica"
      - url: "https://www.renewableenergyworld.com/feeds/all/"
        name: "Renewable Energy World"
      - url: "https://insideclimatenews.org/feed/"
        name: "Inside Climate News"

storage:
  type: "airtable"
  enabled: true

schedule:
  interval: 3600
